### PR TITLE
Add setticketmaxprice RPC, a few doc fixes.

### PR DESCRIPTION
**Pull request by chappjc**
Add the SetTicketMaxPrice RPC.
Correct four copy/paste documentation errors, and another small doc typo.
For [testGetSetTicketMaxPrice in rpctest](https://github.com/chappjc/dcrwallet/blob/rfp10-m3/rpctest/rpcharness_test.go#L1961).

### CODE REVIEW

**Review by alexlyp — APPROVED** [review]
looks good

**Comment by dajohi** [comment]
OK

**Comment by jcvernaleo** [comment]
Were we waiting on anything to merge this one in?

**Comment by chappjc** [comment]
Not that I was told about.  :)

**Pull request merged**
